# Generated by Django 3.2.6 on 2021-12-12 09:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0004_auto_20200814_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_type', models.CharField(max_length=2000, null=True)),
                ('day', models.CharField(max_length=2000, null=True)),
                ('semester', models.CharField(max_length=2000, null=True)),
                ('faculty', models.CharField(max_length=2000, null=True)),
                ('room', models.CharField(max_length=2000, null=True)),
                ('course_id', models.CharField(max_length=2000, null=True)),
                ('time_slot', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='week_day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=2000),
        ),
    ]
