# Generated by Django 3.2.6 on 2021-12-12 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0005_auto_20211212_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='course_id',
            new_name='course_details',
        ),
    ]
